apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.appName }}-service"
  namespace: default
spec:
  selector:
    app: {{ .Values.appName }}
  ports:
    - port: 8765
      targetPort: 3001
  type: LoadBalancer